// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABAgPtdOzCrmojYPE4yRdrmFGgM0egHcY',
    appId: '1:40929229124:web:19fc472883a0e723217f11',
    messagingSenderId: '40929229124',
    projectId: 'amv-project-a7f64',
    authDomain: 'amv-project-a7f64.firebaseapp.com',
    storageBucket: 'amv-project-a7f64.firebasestorage.app',
    measurementId: 'G-P06H0XGY9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTMK1sSczr_FlpFtGukuUh_t_0MMh6cQ',
    appId: '1:40929229124:android:61a43e8d360af2e2217f11',
    messagingSenderId: '40929229124',
    projectId: 'amv-project-a7f64',
    storageBucket: 'amv-project-a7f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_lyojScOoztJTXX3pwJLFoI-2YsV2kY',
    appId: '1:40929229124:ios:7e74150698ae46d7217f11',
    messagingSenderId: '40929229124',
    projectId: 'amv-project-a7f64',
    storageBucket: 'amv-project-a7f64.firebasestorage.app',
    iosClientId: '40929229124-nejs28vqotje18md8sce5d3p7ctp2v8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.amvHotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_lyojScOoztJTXX3pwJLFoI-2YsV2kY',
    appId: '1:40929229124:ios:7e74150698ae46d7217f11',
    messagingSenderId: '40929229124',
    projectId: 'amv-project-a7f64',
    storageBucket: 'amv-project-a7f64.firebasestorage.app',
    iosClientId: '40929229124-nejs28vqotje18md8sce5d3p7ctp2v8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.amvHotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABAgPtdOzCrmojYPE4yRdrmFGgM0egHcY',
    appId: '1:40929229124:web:9476c053a8664ba2217f11',
    messagingSenderId: '40929229124',
    projectId: 'amv-project-a7f64',
    authDomain: 'amv-project-a7f64.firebaseapp.com',
    storageBucket: 'amv-project-a7f64.firebasestorage.app',
    measurementId: 'G-ELLT2RK7GN',
  );
}
